tasks:
  - name: start db
    before: |
      cp gitpod.env .env
      cp .gitpod-firebase-sdk.json firebase-sdk.json
    command: yarn run start-db
  - name: start server
    init: yarn install
    command: yarn run dev:watch
    openMode: tab-after

ports:
  - name: redis
    port: 6379
    onOpen: ignore
  - name: postgres
    port: 35432
    onOpen: ignore
  - name: server
    port: 4200
    onOpen: open-browser
    visibility: public
