version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "35432:5432"
    volumes:
      #  - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./db:/docker-entrypoint-initdb.d
  cache:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/docker-entrypoint-initdb.d
