version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - .env
    ports:
      - "35432:5432"
    volumes:
      - ./test_db_init:/docker-entrypoint-initdb.d
  test:
    image: "bobaserver"
    network_mode: "host"
    build:
      context: .
    command: [
        # There is still a race condition here for the init step of the db
        "/usr/src/git/wait-for-it/wait-for-it.sh",
        "127.0.0.1:35432",
        "-t",
        "120",
        "--",
        "npm",
        "run",
        "test",
      ]
    volumes:
      - .:/usr/src/app
      # Below line prevents Docker from mapping the host's node_modules/
      # folder into the container.  We don't want cross-contamination.
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database
