
CREATE TYPE block_type AS ENUM ('rules', 'text', 'subscription');
CREATE TABLE IF NOT EXISTS blocks
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    string_id TEXT NOT NULL,
    title TEXT NOT NULL,
    index BIGINT NOT NULL,
    type block_type NOT NULL
);

CREATE TABLE IF NOT EXISTS realm_homepage_blocks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    realm_id BIGINT REFERENCES realms(id) ON DELETE RESTRICT NOT NULL,
    block_id BIGINT REFERENCES blocks(id) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE IF NOT EXISTS rules
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    index BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS block_rules 
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    block_id BIGINT REFERENCES blocks(id) ON DELETE RESTRICT NOT NULL,
    rule_id BIGINT REFERENCES rules(id) ON DELETE RESTRICT NOT NULL
);

CREATE TABLE IF NOT EXISTS block_subscriptions (
    block_id BIGINT REFERENCES blocks(id) ON DELETE RESTRICT NOT NULL,
    subscription_id BIGINT REFERENCES subscriptions(id) ON DELETE RESTRICT NOT NULL
);