version: 2.1
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          name: create env file
          command: env > .env
      - run:
          name: see files
          command: ls -la
      - run:
          name: build docker
          command: docker-compose -f docker-compose.test.yml build --no-chache
      - run:
          name: run test
          command: docker-compose -f docker-compose.test.yml up
workflows:
  build-and-test:
    jobs:
      - build-and-test
