version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      - node/with-cache:
          steps:
            - run: env > .env
            - run: cat .env
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
