version: 2.1
jobs:
  build-and-test:
    executor:
      machine:
        image: ubuntu-1604:201903-01
    steps:
      - checkout
      - setup_remote_docker
      - run:
        name: Create required .env file
        command: |
          env > .env
    - run:
      name: Run npm
      command: |
        npm install && npm run test-docker
workflows:
  build-and-test:
    jobs:
      - build-and-test
