version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: create env file
          # IMPORTANT: we prefix boba-related env variables with BBENV_ not to accidentally copy
          # CircleCIs' own variables. We then remove the BBENV_ prefix.
          command: env | grep "^BBENV_" | sed "s/BBENV_//" > .env
          environment:
            BBENV_THIS_IS_A_TEST: a_test
      - run:
          name: see files
          command: cat .env
      # - run:
      #     name: stop everything
      #     command: docker-compose -f docker-compose.test.yml down
      # - run:
      #     name: run test
      #     command: docker-compose -f docker-compose.test.yml run --rm test
      # - run:
      #     name: database logs
      #     command: docker-compose logs database
      #     when: on_fail
      # - store_test_results:
      #     path: ./reports/junit/
      # - store_artifacts:
      #     path: ./reports/junit
  open-api-validate:
    machine: true
    steps:
      - checkout
      - run:
          name: create env file
          command: env > .env
      - run:
          name: see files
          command: ls -la
      - run:
          name: stop everything
          command: docker-compose -f docker-compose.open-api.test.yml down
      - run:
          name: run test
          command: docker-compose -f docker-compose.open-api.test.yml run --rm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
  open-api-validate:
    jobs:
      - open-api-validate
