version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build-and-test:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: run test
          command: docker-compose -f docker-compose.test.yml run --rm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
