version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: create env file
          # IMPORTANT: we prefix boba-related env variables with BBENV_ not to accidentally copy
          # CircleCIs' own variables. We then remove the BBENV_ prefix.
          command: env | grep "^BBENV_" | sed "s/BBENV_//" > .env
      - run:
          name: see files
          command: ls -la
      - run:
          name: stop everything
          command: docker-compose -f docker-compose.test.yml down
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: start db
          command: docker-compose -f docker-compose.test.yml up -d database
      - run:
          name: wait for db
          command: dockerize -wait tcp://localhost:${BBENV_POSTGRES_PORT} -timeout 1m
      - run:
          name: db logs
          command: docker-compose logs
          when: on_fail
      - run:
          name: run test
          command: docker-compose -f docker-compose.test.yml run --rm test
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  open-api-validate:
    machine: true
    steps:
      - checkout
      - run:
          name: create env file
          command: env > .env
      - run:
          name: see files
          command: ls -la
      - run:
          name: stop everything
          command: docker-compose -f docker-compose.open-api.test.yml down
      - run:
          name: run test
          command: docker-compose -f docker-compose.open-api.test.yml run --rm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
  open-api-validate:
    jobs:
      - open-api-validate
