version: 2.1
jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: create env file
          # IMPORTANT: we prefix boba-related env variables with BBENV_ not to accidentally copy
          # CircleCIs' own variables. We then remove the BBENV_ prefix.
          command: env | grep "^BBENV_" | sed "s/BBENV_//" > .env
          environment:
            # We add the non-secret but necessary environment variables here too so builds can correctly run
            # for contributors who are using untrusted forks.
            BBENV_POSTGRES_USER: the_amazing_bobaboard2
            BBENV_POSTGRES_PASSWORD: how_secure_can_this_db_be
            BBENV_POSTGRES_DB: bobaboard_test
            BBENV_POSTGRES_PORT: 35432
            BBENV_DATABASE_URL: postgres://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@localhost:\${POSTGRES_PORT}/\${POSTGRES_DB}
      - run:
          name: see files
          command: ls -la
      - run:
          name: stop everything
          command: docker-compose -f .docker/docker-compose.test.yml down
      - run:
          name: run test
          command: docker-compose -f .docker/docker-compose.test.yml run --rm test
      - run:
          name: database logs
          command: docker-compose logs database
          when: on_fail
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  open-api-validate:
    machine: true
    steps:
      - checkout
      - run:
          name: create env file
          command: env > .env
      - run:
          name: see files
          command: ls -la
      - run:
          name: stop everything
          command: docker-compose -f .docker/docker-compose.open-api.test.yml down
      - run:
          name: run test
          command: docker-compose -f .docker/docker-compose.open-api.test.yml run --rm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
  open-api-validate:
    jobs:
      - open-api-validate
