version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: env > .env
            - run: cat .env
            - run: npm install
            - run: npm test
workflows:
  build-and-test:
    jobs:
      - build-and-test
